$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
type: command
code: src/
command: >-
  python index.py \
    --data_path ${{inputs.data}} \
    --threads 14 \
    --output_dir ${{outputs.result}} \
    --fs_score 0.99 \
    --pident 50  \
    --evalue 1e-5

inputs:
  data:
    type: uri_folder
    path: azureml:diamond_ensenble@latest
    mode: ro_mount

outputs:
  result:
    type: uri_folder
    # Job 완료 후 자동 업로드
    mode: rw_mount

compute: azureml:github
environment: azureml:ensemble-env@latest
# Job 실험명과 task 명 지정. 미기재 해도 됨.
experiment_name: Diamond_Github
display_name: "Diamond Github"
