$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
type: command
code: ../src
command: >-
  python input.py
    --data_path ${{inputs.cafa_data}} 
    --threads 24
    --output_dir ${{outputs.model_output}}

inputs:
  cafa_data:
    type: uri_folder
    path: azureml:diamond_ensenble@latest
    mode: ro_mount

outputs:
  model_output:
    type: uri_folder
    # Job 완료 후 자동 업로드
    mode: upload

compute: azureml:cpu-32core-cluster
environment: azureml:ensemble-env@latest
# Job 실험명과 task 명 지정. 미기재 해도 됨.
experiment_name: Diamond_Github
display_name: "Diamond Github"
